# -*- coding: utf-8 -*-
"""Proyecto - Actividad 1 - Clase 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtlZWCnhkRZPwJ24yxzz7UjKxTy79UsA
"""

import math

calcular="S"
area=0

while calcular=="S":
  figura=input("Ingrese figura a calcular (C para cuadrado, R para rectángulo, O para círculo): ")
  if figura!="C" and figura!="R" and figura!="O":
    print("Incorrecto. Ingrese una opción correcta.")
    figura=input("Ingrese figura a calcular (C para cuadrado, R para rectángulo, O para círculo: ")
  if figura=="C":
    lado=float(input("Ingrese medida del lado del cuadrado: "))
    area=lado*lado
  if figura=="O":
    radio=float(input("Ingrese medida del radio del círculo: "))
    area=math.pi*(radio**2)
  if figura=="R":
    lado1=float(input("Ingrese medida del primer lado del rectángulo: "))
    lado2=float(input("Ingrese medida del segundo lado del rectángulo: "))
    area=lado1*lado2
  calcular=input("¿Continuar? (S para sí, N para no)")

print(area)

import math

def area_circulo(radio):
  return math.pi*(radio**2)

def area_cuadrado(lado):
  return lado**2

def area_rectangulo(lado1,lado2):
  return lado1*lado2

#area_circulo(2)
#area_cuadrado(4)
#area_rectangulo(2,4)

def linea_media_rectangulo(lado1,lado2):
  return math.sqrt((lado1**2)+(lado2**2))

#linea_media_rectangulo(2,4)

import math

def area_circulo(radio):
  return math.pi*(radio**2)

def area_cuadrado(lado):
  return lado**2

def area_rectangulo(lado1,lado2):
  return lado1*lado2

#area_circulo(2)
#area_cuadrado(4)
#area_rectangulo(2,4)

#def linea_media_rectangulo(lado1,lado2):
#  return math.sqrt((lado1**2)+(lado2**2))

#linea_media_rectangulo(2,4)

import math

def area_perimetro_circulo(radio):
  area_o=math.pi*(radio**2)
  peri_o=math.pi*(radio*2)
  print(area_o)
  print(peri_o)

def area_perimetro_cuadrado(lado):
  area_c=lado**2
  peri_c=lado*4
  print(area_c)
  print(peri_c)

def area_perimetro_rectangulo(lado1,lado2):
  area_r=lado1*lado2
  peri_r=2*(lado1+lado2)
  print(area_r)
  print(peri_r)

#area_perimetro_circulo(3.5)
#area_perimetro_cuadrado(4)
#area_perimetro_rectangulo(2,4)